// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfhT25dpUA8bUA9qCkVdf7kUVcLdgiMyE',
    appId: '1:543156959651:web:9e90a12f2e14c3bb5c8216',
    messagingSenderId: '543156959651',
    projectId: 'flutterhw-f41e8',
    authDomain: 'flutterhw-f41e8.firebaseapp.com',
    storageBucket: 'flutterhw-f41e8.appspot.com',
    measurementId: 'G-DD58K725D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt-BnZhxv31OP10vdoyCM0GeM7NHOtFx8',
    appId: '1:543156959651:android:5bff972dd31119365c8216',
    messagingSenderId: '543156959651',
    projectId: 'flutterhw-f41e8',
    storageBucket: 'flutterhw-f41e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQWmEPYlUC0sDv9WbHtqoJZcdm-Rwcqlc',
    appId: '1:543156959651:ios:c4d1791443595a495c8216',
    messagingSenderId: '543156959651',
    projectId: 'flutterhw-f41e8',
    storageBucket: 'flutterhw-f41e8.appspot.com',
    iosBundleId: 'com.codegemz.helloWorld',
  );
}
